name = "gcm-server"
main = "worker.js"
compatibility_date = "2025-12-13"
account_id = "cdcf0f97e5d4512450d210d96d9d5e29"
workers_dev = true

[vars]
USER_ID = "v2up"
FALLBACK_IPS = "proxyip.us.cmliussss.net,tw.william.us.ci"
DYNAMIC_NODES_URL = "https://proxy.ssdxzy.cc.cd/api/nodes?region=SG&limit=10&format=json"
ENABLE_FALLBACK = "true"
CONNECT_TIMEOUT = "1000"
ENABLE_LOGGING = "false"
MAX_STREAMS_PER_CONNECTION = "16"
ENABLE_DYNAMIC_NODES = "true"
DYNAMIC_NODES_TIMEOUT = "3000"

[[routes]]
pattern = "gcm.ics.de5.net"
custom_domain = true
